#! /usr/bin/env python
import sys
DOUBLE_SIZE_BYTES=8
if len(sys.argv) != 2:
    sys.stderr.write('Argument is length of FFT frame.\n')
    exit(-1)
N=int(sys.argv[1])
zeros=''.join(map(lambda x : chr(0),xrange((N*DOUBLE_SIZE_BYTES)/2)))
while 1:
    bytes = sys.stdin.read(N*DOUBLE_SIZE_BYTES)
    if len(bytes) != N*DOUBLE_SIZE_BYTES:
        break
    sys.stdout.write(bytes[0:(N*DOUBLE_SIZE_BYTES)/2])
    sys.stdout.write(zeros)
exit(0)
