#!/usr/bin/env python
import struct
import sys
SINE_STRUCT_SIZE=40
tracks={}
while (1):
    data = sys.stdin.read(SINE_STRUCT_SIZE)
    if (len(data) != SINE_STRUCT_SIZE):
        break
    T,A,F,Phi,track = struct.unpack('ddddQ',data)
    if track in tracks.keys():
        tracks[track].append((T,F))
    else:
        tracks[track]=[(T,F)]
for key in tracks.keys():
    for tup in tracks[key]:
        sys.stdout.write("%f %f\n" % tup)
    sys.stdout.write("\n\n") # separate data sets
